micronaut:
  application:
    name: adminApi
  http:
    client:
      log-level: trace

  security:
    enabled: false
  server:
    netty:
      access-logger:
        enabled: true

datasources:
  default:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:33306}/${DB_NAME:kratos}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:secret}
    dialect: MYSQL

jackson:
  property-naming-strategy: LOWER_CAMEL_CASE
  bean-introspection-module: true

jpa:
  default:
    entity-scan:
      packages: 'io.zgate.admin.user.persistence.po'

kratos:
  endpoint:
    admin: "${KRATOS_ADMIN_URL:`http://127.0.0.1:4434`}"
    public: "${KRATOS_PUBLIC_URL:`http://127.0.0.1:4433`}"

keto:
  endpoint:
    read: "${KETO_READ_URL:`http://127.0.0.1:4466`}"
    write: "${KETO_WRITE_URL:`http://127.0.0.1:4467`}"