micronaut:
  application:
    name: userAdminApi
  http:
    client:
      log-level: trace
      

datasources:
  default:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:33306}/${DB_NAME:kratos}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:secret}
    dialect: MYSQL

jackson:
  property-naming-strategy: SNAKE_CASE

jpa:
  default:
    entity-scan:
      packages: 'io.zgate.useradmin.server.persistence.po'

kratos:
  endpoint:
    admin: ${KRATOS_ADMIN_URL:http://127.0.0.1:4434}
    public: ${KRATOS_PUBLIC_URL:http://127.0.0.1:4433}
